# .github/workflows/main.yml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      app:
        image: docker://mlops_nba:latest
        ports:
          - 8000:8000
        options: --network-alias app

    steps:
    - uses: actions/checkout@v2

    # Pas besoin de créer un réseau Docker explicitement, GitHub Actions gère cela pour vous

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mlops_nba

    # L'exécution de l'application se fait implicitement via les services, donc pas besoin de l'étape "Run the FastAPI app"

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push to DockerHub
      run: |
        docker tag mlops_nba:latest ${{ secrets.DOCKERHUB_USERNAME }}/my-mlops_nba:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlops_nba:latest
